// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAlarmStateChange();
void onResetAlarmChange();

String alarmText;
float temperature;
bool alarmState;
bool resetAlarm;

void initProperties(){

  ArduinoCloud.addProperty(alarmText, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(alarmState, READWRITE, ON_CHANGE, onAlarmStateChange);
  ArduinoCloud.addProperty(resetAlarm, READWRITE, ON_CHANGE, onResetAlarmChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
